# Generated by Django 3.0.6 on 2020-05-26 23:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_friendship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='friendship',
            name='date_include',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 23, 15, 46, 141551, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='friendship',
            table='Friendship',
        ),
    ]
