# Generated by Django 3.0.6 on 2020-06-01 15:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20200526_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='date_include',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 15, 50, 32, 392579, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.AuthUser'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='me',
            field=models.IntegerField(),
        ),
    ]
